services:
  client_web:
    build:
      context: ./Website
      dockerfile: client_web.Dockerfile
      args:
        VITE_API_URL: "http://${EXTERNAL_IP}:8080"
    ports:
      - "8081:4173"
    depends_on:
      - client_mobile
      - server
    environment:
      VITE_API_URL: "http://${EXTERNAL_IP}:8080"
  server:
    build:
      context: ./Api
      dockerfile: server.Dockerfile
    ports:
      - '8080:8000'
    volumes:
      - apk:/apk/
    env_file:
      - .env
    hostname: api
    depends_on:
      - client_mobile
  client_mobile:
    build:
      context: ./App
      dockerfile: client_mobile.Dockerfile
      args:
        - API_URL=http://${EXTERNAL_IP}:8080
    volumes:
      - apk:/apk/
    command: /bin/bash -c "rm /apk/*; cp /usr/src/app/android/app/build/outputs/apk/release/app-release.apk /apk/client.apk"
volumes:
  apk: