name: Test the api

on:
  workflow_dispatch:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Api
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Python
        run: ./install.sh

      - name: Setup Google service
        run: echo "${{ secrets.GOOGLE_SERVICE }}" > ./secrets/Gooogle.json && cat ./secrets/Gooogle.json
      
      - name: Test api
        run: ./run.sh tests
        env:
          APP_NAME: ${{ vars.APP_NAME }}
          APP_VERSION: ${{ vars.APP_VERSION }}
          JWT_ALGORITHM: "HS256"
          JWT_EXPIRE_DAYS: 1
          JWT_EXPIRE_SECONDS: 3600
          REDIRECT_URI: ${{ vars.REDIRECT_URI }}
          SQL_TEST_URL: "sqlite:///./area_test.db"
          SQL_URL: ${{ vars.SQL_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
