name: Test the api

on:
  workflow_dispatch:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    env:
      APP_NAME: "${{ env.APP_NAME }}"
      APP_VERSION: "${{ env.APP_VERSION }}"
      JWT_ALGORITHM: "HS256"
      JWT_EXPIRE_DAYS: 1
      JWT_EXPIRE_SECONDS: 3600
      REDIRECT_URI: "${{ env.REDIRECT_URI }}"
      SQL_TEST_URL: "sqlite:///./area_test.db"
      SQL_URL: "${{ env.SQL_URL }}"
      JWT_SECRET: "${{ secrets.JWT_SECRET }}"
    environment: Api
    defaults:
      run:
        working-directory: ./Api
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Python
        run: ./install.sh

      - name: Setup Google service
        run: echo "${{ secrets.GOOGLE_SERVICE }}" > ./secrets/Gooogle.json && cat ./secrets/Gooogle.json
      
      - name: Test api
        run: ./run.sh tests
