name: Test the api

on:
  workflow_dispatch:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    environment: Api
    defaults:
      run:
        working-directory: ./Api
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Python
        run: ./install.sh
      
      - name: Test api
        run: ./run.sh tests

      - name: Setup env
        run: env > .env
