name: Test the api

on:
  workflow_dispatch:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    environment: Api
    defaults:
      run:
        working-directory: ./Api
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Python
        run: ./install.sh
      
      - name: Test api
        run: ./run.sh tests
        env:
          APP_NAME: ${{ env.APP_NAME }}
          APP_VERSION: ${{ env.APP_VERSION }}
          JWT_ALGORITHM: ${{ env.JWT_ALGORITHM }}
          JWT_EXPIRE_DAYS: ${{ env.JWT_EXPIRE_DAYS }}
          JWT_EXPIRE_SECONDS: ${{ env.JWT_EXPIRE_SECONDS }}
          REDIRECT_URI: ${{ env.REDIRECT_URI }}
          SQL_TEST_URL: ${{ env.SQL_TEST_URL }}
          SQL_URL: ${{ env.SQL_URL }}
          JWT_SECRETS: ${{ secrets.JWT_SECRETS }}
          
          
